[workspace]
resolver = "2"
members = ["crates/aa-rom", "crates/aa-extract", "crates/aa-wasm", "crates/aa-verify", "crates/aa-ctr"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
publish = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
